version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: telegram_ai_bot_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: telegram_ai_bot
      POSTGRES_USER: ai_user
      POSTGRES_PASSWORD: ai_password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
